// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCneAEtN5jUj4MDMXTdk5v7m7soe-2Fy5Y',
    appId: '1:617885300263:web:5a0ea5a1b4e6cd6abe4002',
    messagingSenderId: '617885300263',
    projectId: 'regl-cycle-app',
    authDomain: 'regl-cycle-app.firebaseapp.com',
    storageBucket: 'regl-cycle-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsHSOHLL6EU0OuPju0pq4W9gU6jeNlonE',
    appId: '1:617885300263:android:c629213ce57a5ca8be4002',
    messagingSenderId: '617885300263',
    projectId: 'regl-cycle-app',
    storageBucket: 'regl-cycle-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlxihFKmPpmdH1mgb2SNiQFElGUc4Q1Ts',
    appId: '1:617885300263:ios:3e4d0126d85155b7be4002',
    messagingSenderId: '617885300263',
    projectId: 'regl-cycle-app',
    storageBucket: 'regl-cycle-app.appspot.com',
    iosBundleId: 'com.example.reglCycleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlxihFKmPpmdH1mgb2SNiQFElGUc4Q1Ts',
    appId: '1:617885300263:ios:954dab763a4bd1b7be4002',
    messagingSenderId: '617885300263',
    projectId: 'regl-cycle-app',
    storageBucket: 'regl-cycle-app.appspot.com',
    iosBundleId: 'com.example.reglCycleApp.RunnerTests',
  );
}
